const NEW_CONVERSATION = "main:NEW_CONVERSATION",
    NEW_MESSAGE = "main:NEW_MESSAGE",
    SET_ACTIVE_CONVERSATION = "main:SET_ACTIVE_CONVERSATION"

export {NEW_CONVERSATION, NEW_MESSAGE, SET_ACTIVE_CONVERSATION};
